#pragma once

#include <cstddef>
#include <string>

namespace quackmail {
namespace psl {

// The Public Suffix List, bundled (core/src/psl_data.cpp, regenerated by
// tools/gen_psl.py). The build fetches nothing, so the data is checked in.
extern const char *const kPslChunks[];
extern const size_t kPslChunkCount;
extern const size_t kPslRuleCount;
// Rules before this index are the ICANN (registrar-assigned) section; the rest
// are the private section that delegating providers add for themselves.
extern const size_t kPslIcannRules;

// The public suffix of `domain` — the part nobody can register directly, per
// the algorithm at https://publicsuffix.org/list/ (wildcards, "!" exceptions,
// and the "unlisted TLD is itself a suffix" default). Returns lowercase.
std::string PublicSuffix(const std::string &domain);

// The registrable domain: the public suffix plus one more label. This is
// DMARC's "organizational domain" (RFC 7489 §3.2). Returns an empty string when
// `domain` is nothing but a public suffix, since there is no registrable name.
std::string RegistrableDomain(const std::string &domain);

} // namespace psl
} // namespace quackmail
