#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace quackmail {
namespace tz {

// The IANA time zone database, bundled (core/src/tzdata.cpp, regenerated by
// tools/gen_tzdata.py). The build fetches nothing, so the data is checked in —
// the same arrangement psl.hpp describes for the Public Suffix List.
//
// Why bundled rather than borrowed:
//
//   - Not DuckDB's `icu` extension. A calendar that only works when an optional
//     extension happens to be installed is not a calendar, and the tree
//     deliberately stopped depending on icu.
//   - Not /usr/share/zoneinfo at runtime. Minimal containers routinely ship
//     without it, and reading it would make two installs of the same release
//     disagree about when a meeting is, based on their base image.
//
// The cost is that this is dated data: zones change by political decree several
// times a year. Version() is surfaced in the admin console so an operator can
// see what they are running, and refreshing it is a generator run plus a commit.
//
// Everything here works in seconds. A "wall clock" value is seconds since the
// epoch *as if the local time were UTC* — the representation a form field
// naturally produces, and the one iCalendar's local DATE-TIME form describes.

// The bundled release, e.g. "2026a". Never empty.
const char *Version();

// Is this a zone we know? Accepts the backward-compatibility names too, so
// "US/Eastern" and "Asia/Calcutta" resolve.
bool IsKnown(const std::string &tzid);

// The canonical name for a zone: "US/Eastern" -> "America/New_York". Returns ""
// when the zone is unknown, and the input unchanged when it is already
// canonical.
std::string Canonical(const std::string &tzid);

// Every canonical zone, sorted — for a picker. Links are deliberately excluded:
// offering both "US/Eastern" and "America/New_York" in one list is noise.
std::vector<std::string> List();

// The offset east of UTC in force at `utc`, in seconds, plus whether daylight
// saving applies and the abbreviation ("EST", "AEDT", "+0530"). False when the
// zone is unknown, leaving the outputs untouched.
//
// Past the last stored transition the zone's POSIX rule is applied, so a date
// in 2050 gets the right offset rather than being frozen at whatever the last
// recorded transition left in force.
bool OffsetAt(const std::string &tzid, int64_t utc, int &offset_secs, bool &is_dst, std::string &abbrev);

// Wall clock in `tzid` -> UTC. False when the zone is unknown.
//
// Two local times are not a simple inverse, and both are flagged rather than
// hidden:
//
//   `ambiguous`   the clock went back, so this wall time happens twice. RFC 5545
//                 wants the earlier one, which is what is returned.
//   `nonexistent` the clock went forward, so this wall time never happens. The
//                 result is shifted forward by the size of the gap, which is
//                 what every calendar client does with an event scheduled into
//                 one.
bool ToUtc(const std::string &tzid, int64_t local_wall, int64_t &utc, bool &ambiguous, bool &nonexistent);

// UTC -> wall clock in `tzid`. Returns `utc` unchanged for an unknown zone, so
// a display path always renders something.
int64_t FromUtc(const std::string &tzid, int64_t utc);

// ---- the generated tables ------------------------------------------------
// Declared here so tzdata.cpp has something to define; not part of the API.

struct ZoneType {
	int32_t offset;   // seconds east of UTC
	uint8_t is_dst;   // 0/1
	uint8_t abbr_idx; // index into the zone's abbreviation blob
};

struct Zone {
	const char *name;
	const int64_t *transitions; // ascending UTC seconds
	const uint8_t *type_at;     // which type applies from transitions[i] onward
	size_t transition_count;
	const ZoneType *types;
	size_t type_count;
	const char *abbrs;  // NUL-separated, indexed by ZoneType::abbr_idx
	const char *posix;  // TZ rule for times past the last transition; "" if none
	uint8_t first_type; // type in force before the first transition
	// Should this name appear in a picker? False for the legacy spellings
	// (US/Eastern, EST, Japan) — still resolvable, just not worth offering
	// beside the Area/Location name they are an alias for. Decided by the
	// generator so the rule lives in exactly one place.
	uint8_t selectable;
};

struct Link {
	const char *from; // "US/Eastern"
	const char *to;   // "America/New_York"
};

extern const Zone kZones[];
extern const size_t kZoneCount;
extern const Link kLinks[];
extern const size_t kLinkCount;
extern const char *const kTzVersion;

} // namespace tz
} // namespace quackmail
