#pragma once

#include <cstddef>
#include <string>

namespace duckdb {
namespace qmweb {

// The compiled-in contents of http/assets/. web_assets.cpp is generated by
// tools/gen_assets.py and committed, on the same terms as core/src/psl_data.cpp:
// the build fetches and generates nothing.

struct Asset {
	const char *name;    // hashed, as it appears in the URL: "qc.9f3a1c2b.css"
	const char *logical; // as it appears in http/assets/: "qc.css"
	const char *mime;    // decided by the generator, never from the request
	const unsigned char *data;
	size_t size;
	const char *etag; // the same content hash the name carries
};

// Look an asset up by its hashed name. Nothing else matches: the logical name
// is not a valid URL, so there is exactly one path per set of bytes.
const Asset *FindAsset(const std::string &name);

// The URL for a logical name — "/static/qc.9f3a1c2b.css". Page code always goes
// through this and never types a hash, so regenerating the assets is enough to
// move every reference.
std::string AssetUrl(const char *logical);

} // namespace qmweb
} // namespace duckdb
