#!/usr/bin/env python3
"""Regenerate http/src/web_assets.cpp from the files in http/assets/.

Run this after editing anything under http/assets/, and commit the result. The
build never generates it: release.yml has no step that could, and an extension
that needed one could not be built offline. The generated file is therefore part
of the source tree, exactly like core/src/psl_data.cpp.

    python3 tools/gen_assets.py            # rewrite http/src/web_assets.cpp
    python3 tools/gen_assets.py --check    # exit 1 if it is out of date (CI)

Asset URLs carry a content hash (`qc.9f3a1c2b.css`), which is what lets them be
served `immutable` with a one-year lifetime: the URL changes when the bytes do,
so there is never a stale copy to revalidate and never a cache to bust by hand.
"""
import argparse
import hashlib
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "http", "assets")
OUT = os.path.join(REPO, "http", "src", "web_assets.cpp")

# The served Content-Type, keyed by extension. Deliberately a fixed table rather
# than anything derived at request time: the type is decided here, once, from a
# filename we control, so a file added to http/assets/ with an unexpected suffix
# fails the generator instead of being served as something a browser will sniff.
MIME = {
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".woff2": "font/woff2",
}


def collect():
    """Every asset, sorted, as (logical_name, hashed_name, mime, bytes)."""
    out = []
    for name in sorted(os.listdir(SRC)):
        path = os.path.join(SRC, name)
        if not os.path.isfile(path):
            continue
        ext = os.path.splitext(name)[1]
        if ext not in MIME:
            raise SystemExit(f"{name}: no MIME type for '{ext}' — add one to MIME in this script")
        with open(path, "rb") as f:
            data = f.read()
        digest = hashlib.sha256(data).hexdigest()[:8]
        stem, _ = os.path.splitext(name)
        out.append((name, f"{stem}.{digest}{ext}", MIME[ext], data, digest))
    if not out:
        raise SystemExit(f"no assets found in {SRC}")
    return out


def carray(data, indent="    "):
    """A C++ initializer list, 16 bytes to a line."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def emit(assets):
    body = [
        "// Generated by tools/gen_assets.py. Do not edit.",
        "//",
        "// The contents of http/assets/, compiled in. Serving them from memory keeps",
        "// the extension a single loadable file with no data directory to install, and",
        "// it means /static cannot be made to read anything off the filesystem.",
        "",
        '#include "web_assets.hpp"',
        "",
        "#include <cstring>",
        "",
        "namespace duckdb {",
        "namespace qmweb {",
        "namespace {",
        "",
    ]
    for i, (_, _, _, data, _) in enumerate(assets):
        body.append(f"const unsigned char kBytes{i}[] = {{")
        body.append(carray(data))
        body.append("};")
        body.append("")

    body += [
        "const Asset kAssets[] = {",
    ]
    for i, (logical, hashed, mime, data, digest) in enumerate(assets):
        body.append(
            f'    {{"{hashed}", "{logical}", "{mime}", kBytes{i}, sizeof(kBytes{i}), "{digest}"}},'
        )
    body += [
        "};",
        "",
        "const size_t kAssetCount = sizeof(kAssets) / sizeof(kAssets[0]);",
        "",
        "} // namespace",
        "",
        "const Asset *FindAsset(const std::string &name) {",
        "\t// Linear over a handful of entries, matched on the *hashed* name only:",
        "\t// the logical name is never a valid URL, so a stale bookmark 404s rather",
        "\t// than being served a file whose bytes have since changed.",
        "\tfor (size_t i = 0; i < kAssetCount; i++) {",
        "\t\tif (name == kAssets[i].name) {",
        "\t\t\treturn &kAssets[i];",
        "\t\t}",
        "\t}",
        "\treturn nullptr;",
        "}",
        "",
        "std::string AssetUrl(const char *logical) {",
        "\tfor (size_t i = 0; i < kAssetCount; i++) {",
        "\t\tif (std::strcmp(logical, kAssets[i].logical) == 0) {",
        '\t\t\treturn std::string("/static/") + kAssets[i].name;',
        "\t\t}",
        "\t}",
        "\t// A typo in a logical name is a build-time mistake, but returning the",
        "\t// bare path keeps the page rendering (unstyled) rather than throwing",
        "\t// inside a request thread.",
        '\treturn std::string("/static/") + logical;',
        "}",
        "",
        "} // namespace qmweb",
        "} // namespace duckdb",
        "",
    ]
    return "\n".join(body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the generated file is current; do not write")
    args = ap.parse_args()

    assets = collect()
    text = emit(assets)

    if args.check:
        try:
            with open(OUT, encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            raise SystemExit(f"{OUT} does not exist — run tools/gen_assets.py")
        if current != text:
            raise SystemExit(
                f"{OUT} is out of date with http/assets/ — run tools/gen_assets.py and commit")
        print(f"{OUT} is up to date ({len(assets)} assets)")
        return

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    total = sum(len(a[3]) for a in assets)
    print(f"wrote {OUT}: {len(assets)} assets, {total} bytes")
    for logical, hashed, mime, data, _ in assets:
        print(f"  {logical:16} -> /static/{hashed}  ({len(data)} bytes, {mime})")


if __name__ == "__main__":
    main()
