#!/usr/bin/env python3
"""Regenerate core/src/psl_data.cpp from the Public Suffix List.

Run this by hand when the list should be refreshed, and commit the result. The
build never fetches anything: release.yml has no network step, and an extension
that needed one could not be built offline. The generated file is therefore part
of the source tree, like any other bundled data.

    python3 tools/gen_psl.py            # fetch and rewrite core/src/psl_data.cpp
    python3 tools/gen_psl.py --from FILE # use a local copy instead

The canonical URL is publicsuffix.org; the GitHub mirror is a fallback for
networks that cannot reach it.
"""
import argparse
import os
import sys
import urllib.request

URLS = [
    "https://publicsuffix.org/list/public_suffix_list.dat",
    "https://raw.githubusercontent.com/publicsuffix/list/main/public_suffix_list.dat",
]

ICANN_END = "===END ICANN DOMAINS==="
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "core", "src", "psl_data.cpp")

# Rules per raw string literal. The standard only guarantees 64 KiB per string
# literal, and while gcc and clang cope with far more, there is no reason to
# lean on that for a generated file.
CHUNK = 2000


def fetch(source):
    if source:
        with open(source, encoding="utf-8") as f:
            return f.read()
    last = None
    for url in URLS:
        try:
            with urllib.request.urlopen(url, timeout=60) as r:
                return r.read().decode("utf-8")
        except Exception as e:  # noqa: BLE001 - report and try the mirror
            last = e
            print(f"  {url}: {e}", file=sys.stderr)
    raise SystemExit(f"could not fetch the list: {last}")


def parse(text):
    """Return (rules, icann_count) with the ICANN section first."""
    icann, private, in_private = [], [], False
    for line in text.splitlines():
        if ICANN_END in line:
            in_private = True
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        (private if in_private else icann).append(line)
    return icann + private, len(icann)


def emit(rules, icann_count):
    chunks = ["\n".join(rules[i:i + CHUNK]) for i in range(0, len(rules), CHUNK)]
    for c in chunks:
        # A raw string literal ends at the delimiter, so it must not appear.
        assert ')PSL"' not in c, "delimiter collision"
    body = [
        "// Generated by tools/gen_psl.py. Do not edit.",
        "//",
        "// The Public Suffix List (https://publicsuffix.org/), MPL 2.0. The ICANN",
        "// section comes first, then the private section; kPslIcannRules marks the",
        "// boundary so a caller can restrict itself to the registrar-assigned part.",
        "",
        '#include "quackmail/psl.hpp"',
        "",
        "namespace quackmail {",
        "namespace psl {",
        "",
        f"const size_t kPslIcannRules = {icann_count};",
        f"const size_t kPslRuleCount = {len(rules)};",
        "",
        "const char *const kPslChunks[] = {",
    ]
    for c in chunks:
        body.append(f'    R"PSL({c})PSL",')
    body += [
        "};",
        "",
        f"const size_t kPslChunkCount = {len(chunks)};",
        "",
        "} // namespace psl",
        "} // namespace quackmail",
        "",
    ]
    return "\n".join(body)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="source", help="read the list from a file")
    args = ap.parse_args()

    rules, icann = parse(fetch(args.source))
    if icann < 5000 or len(rules) < 6000:
        raise SystemExit(f"list looks truncated: {icann} ICANN of {len(rules)} rules")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(emit(rules, icann))
    print(f"wrote {OUT}: {len(rules)} rules ({icann} ICANN, {len(rules) - icann} private)")


if __name__ == "__main__":
    main()
